name: aplikasi_whatsapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  image_picker: ^1.1.0
  file_picker: ^5.2.10
  intl: ^0.18.1
  path_provider: ^2.0.15
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
